tasks:
  # Install Scala-cli
  - command: |
      curl -s --compressed "https://virtuslab.github.io/scala-cli-packages/KEY.gpg" | sudo apt-key add -
      sudo curl -s --compressed -o /etc/apt/sources.list.d/scala_cli_packages.list "https://virtuslab.github.io/scala-cli-packages/debian/scala_cli_packages.list"
      sudo apt update
      sudo apt install scala-cli
  - command: scala-cli setup-ide .
